spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003171
  
server:
  port: 8180
  
logging:
  file: /Users/chenlushun/opt/logs/100003171/apollo-configservice.log